<b> Shreya Kapoor  <br> 
kapoorshreya18@gmail.com <br>
Intro to CS <br> 
MSc Life Science Informatics <br> 
WS 2018


<b> Excercise 1. (Matrix Functions)

In [1]:
from random import randint   #code for generating random numbers 

<b> • First think how we can present a matrix in the data structures we learnt so far then write a function that takes two arguments, the number of rows and columns, and returns matrix of size rows × column filled with random values between −5 to 5.(3P)


In [2]:
def create_mat(m,n): 
    #empty list for storing the result after the addition of the matrices
    mat = []
    for i in range(m): 
        #this a new list defined for each row! 
        msub = []
        for j in range(n): 
            # a random integer is generated for each element!
            msub.append(randint(-5,5))
        mat.append(msub)
    return (mat)            
    
    

<b> • Write function addition(M1,M2) which takes M1 and M2 matrices as input and calculates the addition of them. In matrix addition both matrices must have the same size, if M1 and M2 have different size the function should raise an exception. (4P)


In [3]:
def addition(M1,M2): 
    # check the condition of no. of rows and cols in M1 = M2
    if(len(M1)==len(M2) and len(M1[0])==len(M2[0])):
        #the whole addition matrix
        matsum = []
        for i in range(len(M1)): 
            # the list of each row!
            matr = []
            for j in range(len(M1[0])): 
                matr.append(M1[i][j]+M2[i][j])
            matsum.append(matr)
        return matsum
    else: 
        raise Exception('Size not compatible') 
        

                

<b> • Write function multiplication(M1,M2) which takes M1 and M2 matrices as input and calcu- lates matrix multiplication (not component-wise multiplication). Validate the inputs for matrix multiplication and raise an exception if necessary. (5P)

In [4]:
def multiply(M1,M2): 
    m = len(M1)
    n = len(M1[0])
    n1= len(M2)
    p = len(M2[0])
    #checking the condition that no. of columns in M1 = no. of rows in M2
    if (n==n1): 
        #the whole matrix 
        mat3 = []
        for i in range(m): 
            #submatrix of each row
            matrow = []
            for k in range(p): 
                # each element is calculatd as a sum of component wise addition of vectors
                num = 0
                for j in range(n): 
                    num += M1[i][j]*M2[j][k]
                matrow.append(num)
            mat3.append(matrow)
        return mat3 
    else: 
        raise Exception('Column Length of 1st Matrix not equal to Row length of 2nd Matrix')
        

In [5]:
# when without exception case
l = input('Enter no. of rows and columns for the matrix M1 (separated by spaces) : ')
m = input('Enter no. of rows and columns for the matrix M2 (separated by spaces) : ')
l = l.split(' ')
m = m.split(' ')
mat1 = create_mat(int(l[0]), int(l[1]))
mat2 = create_mat(int(m[0]), int(m[1]))
print ("First Generated matrix \n", mat1)
print ("\n Second Generated matrix \n", mat2)
print ('Result after addition! \n',addition(mat1,mat2))
print ('Result after multiplication! \n', multiply(mat1,mat2)) 
# the array so returned is a list of lists

Enter no. of rows and columns for the matrix M1 (separated by spaces) : 3 3
Enter no. of rows and columns for the matrix M2 (separated by spaces) : 3 3
First Generated matrix 
 [[4, 3, 0], [0, 4, -5], [4, -2, 2]]

 Second Generated matrix 
 [[1, 5, 1], [-1, -5, -4], [4, -2, 4]]
Result after addition! 
 [[5, 8, 1], [-1, -1, -9], [8, -4, 6]]
Result after multiplication! 
 [[1, 5, -8], [-24, -10, -36], [14, 26, 20]]


<b> Checking the validity of the solutions with the help of numpy library! 

In [6]:
import numpy as np

mat1n = np.array(mat1)
mat2n = np.array(mat2)
mat3 = np.add(mat1,mat2)

print ('Addition matrix \n', mat3)
mul = np.matmul(mat1n,mat2n)
print ('Multiplication Matrix \n', mul)

Addition matrix 
 [[ 5  8  1]
 [-1 -1 -9]
 [ 8 -4  6]]
Multiplication Matrix 
 [[  1   5  -8]
 [-24 -10 -36]
 [ 14  26  20]]


<b> When the case of an exception arises! 

In [7]:

l = input('Enter no. of rows and columns for the matrix M1 (separated by spaces) : ')
m = input('Enter no. of rows and columns for the matrix M2 (separated by spaces) : ')
l = l.split(' ')
m = m.split(' ')
mat1 = create_mat(int(l[0]), int(l[1]))
mat2 = create_mat(int(m[0]), int(m[1]))
print ("First Generated matrix \n", mat1)
print ("\n Second Generated matrix \n", mat2)

Enter no. of rows and columns for the matrix M1 (separated by spaces) : 2 3
Enter no. of rows and columns for the matrix M2 (separated by spaces) : 5 3
First Generated matrix 
 [[5, -3, 5], [2, -1, 1]]

 Second Generated matrix 
 [[-2, -3, -1], [-2, -5, 4], [5, 0, 1], [-1, 5, 3], [4, 2, -1]]


In [8]:
print ('Result after addition! \n',addition(mat1,mat2))

Exception: Size not compatible

In [ ]:
print ('Result after multiplication! \n', multiply(mat1,mat2))


<b> A brain atlas annotates each location in the brain with a numerical code that indicates the corresponding anatomical structure. In this task, you will read the assignment from numerical labels to textual anatomical labels for two brain atlases from XML files and represent them as Python dictionaries. Please download two provided files ”HarvardOxford-Cortical.xml” and ”HarvardOxford-Subcortical.xml” from lecture homepage and do the following tasks.

<b> Notice: For these tasks you don’t have to write (or use) a full XML parser, you can use the provided methods in the lecture to read the atlas file and take benefit of string methods to extract information from atlas file.

<b> • Write function AtlasDict(input) that takes atlas xml file path and returns the dictionary of in- dex to structural name. For example in ”Harvard-Oxford Cortical Structural Atlas”, the index of ”Postcentral Gyrus” is 16. (8p)


In [9]:
def AtlasDict(filename):
    with open (filename, 'r') as f: 
        a = f.read()
        c = a.split('<label')
        c = c[1:]
        index =[]
        descr = []
        for i in range(len(c)): 
            index.append(c[i].split('index=\"')[1].split('\"')[0]) 
            descr.append(c[i].split('</label>\n')[0].split('>')[1])
        dict1 ={}
        keys = index
        k = 0
        for i  in keys: 
            dict1[i] = descr[k]
            k+=1
    return dict1

<b>• Write function summarize(input,output) that takes atlas xml file path and output path and produces a new file that contains the name of atlas, the short name, structures name and corre- sponding index and the total number of structural region. (5p)

In [10]:
def summarize(inputfile, outputfile): 
    with open(inputfile,'r') as f: 
        a = f.read()
    b = a.split('<name>')
    b = b[1].split('</name')[0]
    c = a.split('<shortname>')
    c = c[1].split('</shortname')[0]
    dict1 = {}
    dict1['Atlas name'] = b
    dict1['Atlas short'] = c
    dict2 = AtlasDict(inputfile) 
    dict1.update(dict2)
    
    with open(outputfile,'w') as f2: 
        for key in dict1: 
            f2.write(key+': '+dict1[key]+'\n')
            print (key+': '+dict1[key]+'\n')
        f2.write('Number of structures in the atlas: '+str(len(dict2.keys())))
        print ('Number of structures in the atlas: '+str(len(dict2.keys())))


<b> For Harvard Oxford Cortical

In [11]:
AtlasDict('/Users/shreyakapoor/Life_Science_Informatics/IntroductiontoCS/HarvardOxford-Cortical.xml')



{'0': 'Frontal Pole',
 '1': 'Insular Cortex',
 '2': 'Superior Frontal Gyrus',
 '3': 'Middle Frontal Gyrus',
 '4': 'Inferior Frontal Gyrus, pars triangularis',
 '5': 'Inferior Frontal Gyrus, pars opercularis',
 '6': 'Precentral Gyrus',
 '7': 'Temporal Pole',
 '8': 'Superior Temporal Gyrus, anterior division',
 '9': 'Superior Temporal Gyrus, posterior division',
 '10': 'Middle Temporal Gyrus, anterior division',
 '11': 'Middle Temporal Gyrus, posterior division',
 '12': 'Middle Temporal Gyrus, temporooccipital part',
 '13': 'Inferior Temporal Gyrus, anterior division',
 '14': 'Inferior Temporal Gyrus, posterior division',
 '15': 'Inferior Temporal Gyrus, temporooccipital part',
 '16': 'Postcentral Gyrus',
 '17': 'Superior Parietal Lobule',
 '18': 'Supramarginal Gyrus, anterior division',
 '19': 'Supramarginal Gyrus, posterior division',
 '20': 'Angular Gyrus',
 '21': 'Lateral Occipital Cortex, superior division',
 '22': 'Lateral Occipital Cortex, inferior division',
 '23': 'Intracalcarin

In [12]:
summarize('/Users/shreyakapoor/Life_Science_Informatics/IntroductiontoCS/HarvardOxford-Cortical.xml', 'op1.txt')

Atlas name: Harvard-Oxford Cortical Structural Atlas

Atlas short: HOCPA

0: Frontal Pole

1: Insular Cortex

2: Superior Frontal Gyrus

3: Middle Frontal Gyrus

4: Inferior Frontal Gyrus, pars triangularis

5: Inferior Frontal Gyrus, pars opercularis

6: Precentral Gyrus

7: Temporal Pole

8: Superior Temporal Gyrus, anterior division

9: Superior Temporal Gyrus, posterior division

10: Middle Temporal Gyrus, anterior division

11: Middle Temporal Gyrus, posterior division

12: Middle Temporal Gyrus, temporooccipital part

13: Inferior Temporal Gyrus, anterior division

14: Inferior Temporal Gyrus, posterior division

15: Inferior Temporal Gyrus, temporooccipital part

16: Postcentral Gyrus

17: Superior Parietal Lobule

18: Supramarginal Gyrus, anterior division

19: Supramarginal Gyrus, posterior division

20: Angular Gyrus

21: Lateral Occipital Cortex, superior division

22: Lateral Occipital Cortex, inferior division

23: Intracalcarine Cortex

24: Frontal Medial Cortex

25: Juxt

In [13]:
AtlasDict('HarvardOxford-Subcortical.xml')

{'0': 'Left Cerebral White Matter',
 '1': 'Left Cerebral Cortex ',
 '2': 'Left Lateral Ventrical',
 '3': 'Left Thalamus',
 '4': 'Left Caudate',
 '5': 'Left Putamen',
 '6': 'Left Pallidum',
 '7': 'Brain-Stem',
 '8': 'Left Hippocampus',
 '9': 'Left Amygdala',
 '10': 'Left Accumbens',
 '11': 'Right Cerebral White Matter',
 '12': 'Right Cerebral Cortex ',
 '13': 'Right Lateral Ventricle',
 '14': 'Right Thalamus',
 '15': 'Right Caudate',
 '16': 'Right Putamen',
 '17': 'Right Pallidum',
 '18': 'Right Hippocampus',
 '19': 'Right Amygdala',
 '20': 'Right Accumbens'}

In [14]:
summarize('HarvardOxford-Subcortical.xml', 'op2.txt')

Atlas name: Harvard-Oxford Subcortical Structural Atlas

Atlas short: HOSPA

0: Left Cerebral White Matter

1: Left Cerebral Cortex 

2: Left Lateral Ventrical

3: Left Thalamus

4: Left Caudate

5: Left Putamen

6: Left Pallidum

7: Brain-Stem

8: Left Hippocampus

9: Left Amygdala

10: Left Accumbens

11: Right Cerebral White Matter

12: Right Cerebral Cortex 

13: Right Lateral Ventricle

14: Right Thalamus

15: Right Caudate

16: Right Putamen

17: Right Pallidum

18: Right Hippocampus

19: Right Amygdala

20: Right Accumbens

Number of structures in the atlas: 21
